### ISSUE TITLE
Select2 causing JQuery Errors

### ISSUE THREAD

**Issue by ndswecker** [ndswecker/SnatchItCore#45]
Console Errors cannot be resolved:
"select2.full.min.js:2 Uncaught ReferenceError: jQuery is not defined
    at select2.full.min.js:2:241
    at select2.full.min.js:2:249
(anonymous) @ select2.full.min.js:2
(anonymous) @ select2.full.min.js:2
en.js:3 Uncaught ReferenceError: jQuery is not defined
    at en.js:3:13
    at en.js:3:755
(anonymous) @ en.js:3
(anonymous) @ en.js:3
django_select2.js:9 Uncaught ReferenceError: jQuery is not defined
    at django_select2.js:9:13
    at django_select2.js:11:2"
  
Automatic focus of search field does not work.

**Comment by ndswecker** [comment]
I have spent all morning trying to resolve this issue and cannot find any solution.

**Comment by ndswecker** [comment]
Ditched select2 in favor of choices.js
Problem solved.
